server:
    port: 8091
spring:
    application:
        name: auth-service
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: 1
        driver-class-name: org.postgresql.Driver
    data:
      redis:
          host: localhost
          port: 6379
    jpa:
        properties:
            hibernate:
                show_sql: true
        hibernate:
            ddl-auto: create-drop
        database-platform: org.hibernate.dialect.PostgreSQLDialect
security:
    jwt:
        secret-key: o9354rn9mm94kmd93d903kj209kksdfkmlsdfkmsdf9341924124
        expiration-time: 600000
