server:
    port: 8081
spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: 1
      driver-class-name: org.postgresql.Driver
    application:
          name: auth-service
    data:
      redis:
        host: localhost
        port: 6379
    jpa:
      hibernate:
        ddl-auto: create-drop
      show-sql: false
      properties:
        hibernate:
          format_sql: true
      open-in-view: false

security:
    jwt:
        secret-key: o9354rn9mm94kmd93d903kj209kksdfkmlsdfkmsdf9341924124
        expiration-time: 600000
