version: '3.8'
services:
  google-drive-gateway-service:
    build: ./api-gateway
    image: google-drive-gateway-service
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    container_name: google-drive-gateway-service
    ports:
      - "8082:8082"
    depends_on:
      - google-drive-gateway-redis
  google-drive-auth-service:
    build: ./auth-service
    image: google-drive-auth-service
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    container_name: google-drive-auth-service
    ports:
      - "8081:8081"
    depends_on:
      - google-drive-auth-postgres
      - google-drive-auth-redis
  google-drive-auth-postgres:
    image: postgres:15-alpine
    container_name: google-drive-auth-postgres
    ports:
      - "8083:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
    restart: unless-stopped
  google-drive-auth-redis:
    image: redis
    container_name: google-drive-auth-redis
    ports:
      - "8084:6379"
    networks:
      - redis-network
  google-drive-gateway-redis:
    image: redis
    container_name: google-drive-gateway-redis
    ports:
      - "8085:6379"
    networks:
      - redis-network
networks:
  redis-network:
    driver: bridge
volumes:
  pgdata: