server:
  port: 8082
  forward-headers-strategy: framework
spring:
    application:
      name: api-gateway
    cloud:
      gateway:
        limiter:
          requestPerMinute: 30
          leakRate: 60000
          maxCapacity: 30
        routes:
          - id: auth-service-route-authenticate
            uri: http://localhost:8081/api/v1/auth/authenticate
            predicates:
              - Method=POST
              - Path=/auth/authenticate
            filters:
              - RewritePath=/auth/authenticate, /api/v1/auth/authenticate
          - id: auth-service-route-register
            uri: http://localhost:8081/api/v1/auth/register
            predicates:
              - Path=/auth/register
              - Method=POST
            filters:
              - RewritePath=/auth/register,/api/v1/auth/register
          - id: drive-service-route
            uri: http://localhost:8086
            predicates:
              - Method=POST, DELETE, PATCH, GET
              - Path=/drive/**
            filters:
              - RewritePath=/drive/(?<segment>.*), /api/v1/drive/$\{segment}


    data:
      redis:
        port: 6378
        host: localhost
        expiration: 60000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8087/eureka/

logging:
  level:
    org.springframework.cloud.gateway: debug
    reactor.netty: debug