spring:
    application:
        name: drive-service
    datasource:
        url: jdbc:postgresql://localhost:5432/google-drive
        username: postgres
        password: 1
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: false
        properties:
            hibernate:
                format_sql: true
        open-in-view: false

    liquibase:
        enabled: true
        change-log: classpath*:db/db.changelog-master.yml

storage:
    minio:
        bucket: user-files
        credentials:
            user: admin
            password: password
        endpoint: http://localhost:9000
server:
    port: 8086
